services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: mock-ease
    depends_on:
      db:
        condition: service_started
    links:
      - db
    environment:
      - DB_HOST=db
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres:12.16-alpine
    restart: always
    environment:
      - POSTGRES_USER=api_mock_user
      - POSTGRES_PASSWORD=api_mock_pass
      - POSTGRES_DB=api_mock
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/main/resources/db/db.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
