CREATE TABLE API_SERVICE
(
    API_SERVICE_ID VARCHAR(64)   NOT NULL PRIMARY KEY,
    NAME           VARCHAR(200)  NOT NULL,
    CATEGORY_ID    VARCHAR(64)   NOT NULL,
    DESCRIPTION    VARCHAR(4000),
    PREFIX         VARCHAR(1000) NOT NULL,
    VERSION        VARCHAR(64)   NOT NULL,
    CREATE_AT      TIMESTAMPTZ   NOT NULL,
    UPDATE_AT      TIMESTAMPTZ   NOT NULL

);

CREATE TABLE API_PATH_STUB
(
    API_PATH_STUB_ID      VARCHAR(64)   NOT NULL PRIMARY KEY,
    API_SERVICE_ID        VARCHAR(64)   NOT NULL,
    NAME                  VARCHAR(200)  NOT NULL,
    OPERATION_ID          VARCHAR(64)   NOT NULL,
    PATH                  VARCHAR(1000) NOT NULL,
    METHOD                VARCHAR(64)   NOT NULL,
    REQUEST_HEADERS       TEXT          NOT NULL,
    VALIDATION_ENABLED    BOOLEAN       NOT NULL,
    REQUEST_SCHEMA        TEXT,
    REQUEST_DYNAMIC_BODY  BOOLEAN       NOT NULL,
    REQUEST_BODY          TEXT,
    RESPONSE_HTTP_STATUS  VARCHAR(64)   NOT NULL,
    RESPONSE_HEADERS      TEXT,
    RESPONSE_DYNAMIC_BODY BOOLEAN       NOT NULL,
    RESPONSE_BODY         TEXT,
    API_WEBHOOK_ID        VARCHAR(64),
    API_PROXY_ID          VARCHAR(64),
    CREATE_AT             TIMESTAMPTZ   NOT NULL,
    UPDATE_AT             TIMESTAMPTZ   NOT NULL
);

CREATE TABLE API_WEBHOOK
(
    API_WEBHOOK_ID       VARCHAR(64)   NOT NULL PRIMARY KEY,
    URL                  VARCHAR(1000) NOT NULL,
    METHOD               VARCHAR(64)   NOT NULL,
    HEADERS              TEXT,
    REQUEST_DYNAMIC_BODY BOOLEAN       NOT NULL,
    BODY                 TEXT,
    CREATE_AT            TIMESTAMPTZ   NOT NULL,
    UPDATE_AT            TIMESTAMPTZ   NOT NULL
);

CREATE TABLE API_PROXY
(
    API_PROXY_ID VARCHAR(64)   NOT NULL PRIMARY KEY,
    URL          VARCHAR(1000) NOT NULL,
    CREATE_AT    TIMESTAMPTZ   NOT NULL,
    UPDATE_AT    TIMESTAMPTZ   NOT NULL
);

CREATE TABLE API_CATEGORY
(
    API_CATEGORY_ID VARCHAR(64)   NOT NULL PRIMARY KEY,
    NAME            VARCHAR(200)   NOT NULL,
    DESCRIPTION     VARCHAR(4000),
    CREATE_AT       TIMESTAMPTZ   NOT NULL,
    UPDATE_AT       TIMESTAMPTZ   NOT NULL
);



